clusterThis: VRAY_clusterThis_Exception Class Reference
VRAY_clusterThis_Exception Class Reference
#include <VRAY_clusterThis.h>
Public Member Functions
VRAY_clusterThis_Exception (std::string msg, int code)
void what ()
Private Attributes
std::string e_msg
int e_code
Detailed Description
Definition at line 101 of file VRAY_clusterThis.h.
Constructor & Destructor Documentation
VRAY_clusterThis_Exception()
VRAY_clusterThis_Exception::VRAY_clusterThis_Exception (std::string msg, int code)
Definition at line 150 of file VRAY_clusterThis.cpp.
 {
    e_msg = msg;
    e_code = code;
 };
References e_code, and e_msg.
Referenced by VRAY_clusterThis::initialize().
Member Function Documentation
what()
void VRAY_clusterThis_Exception::what () inline
Definition at line 110 of file VRAY_clusterThis.h.
                   {
          std::cout << "VRAY_clusterThis_Exception::what() - VRAY_clusterThis exception:  " << e_msg << endl;
       }
References e_msg.
Referenced by VRAY_clusterThis::getAttributeRefs(), VRAY_clusterThis::render(), and VRAY_clusterThis::runCVEX().
Member Data Documentation
e_code
int VRAY_clusterThis_Exception::e_code private
Definition at line 104 of file VRAY_clusterThis.h.
Referenced by VRAY_clusterThis_Exception().
e_msg
std::string VRAY_clusterThis_Exception::e_msg private
Definition at line 103 of file VRAY_clusterThis.h.
Referenced by VRAY_clusterThis_Exception(), and what().
The documentation for this class was generated from the following files:
VRAY_clusterThis.h
VRAY_clusterThis.cpp