clusterThis: VRAY_clusterThisUtil.cpp File Reference
VRAY_clusterThisUtil.cpp File Reference
Macros
#define __VRAY_clusterThisUtil_cpp__
Functions
static void getRoughBBox (UT_BoundingBox &box, UT_BoundingBox &vbox, const GEO_Point *point, const fpreal scale, const GA_ROAttributeRef &voff, fpreal tscale, const UT_Matrix4 &xform)
********************** MISC. STATIC FUNCTIONS *************************************
static void clampBox (UT_BoundingBox &from, const UT_BoundingBox &to)
static int testClampBox (const UT_BoundingBox &from, const UT_BoundingBox &to)
static short int myPasses (int mode)
static int calculateNewInstPosition (fpreal theta, uint32 i, uint32 j)
static int computeDivs (fpreal inc, fpreal min)
Macro Definition Documentation
__VRAY_clusterThisUtil_cpp__
#define __VRAY_clusterThisUtil_cpp__
Definition at line 13 of file VRAY_clusterThisUtil.cpp.
Function Documentation
calculateNewInstPosition()
static int calculateNewInstPosition (fpreal theta, uint32 i, uint32 j) inline static
Definition at line 846 of file VRAY_clusterThisUtil.cpp.
 {
 #ifdef DEBUG
    cout << "VRAY_clusterThis::calculateNewInstPosition() i: " << i << " j: " << j << endl;
 #endif
    // Calculate a new position for the object ...
 //   fpreal delta = theta * i;
 //   fpreal dx, dy, dz = 0.0;
 //   dx = SYSsin(delta * myFreqX + myOffsetX);
 //   dy = SYScos(delta * myFreqY + myOffsetY);
 //   dz = SYScos(delta * myFreqZ + myOffsetZ);
 //#ifdef DEBUG
 //   cout << "VRAY_clusterThis::calculateNewInstPosition() " << "delta: " << delta << endl;
 //   cout << "VRAY_clusterThis::calculateNewInstPosition() " << "dx: " << dx << " dy: " << dy << " dz: " << dz << endl;
 //#endif
 //   myNoise.setSeed(myPointAttributes.id);
    // Calculate a bit of noise to add to the new position ...
    // TODO:
 //   fpreal noise_bias = (myNoise.turbulence(myPointAttributes.myPos, myFractalDepth, myRough, myNoiseAtten) * myNoiseAmp) + 1.0;
 //      UT_Vector3 myNoiseVec;
    // myNoise.turbulence(myPos, myFractalDepth, myNoiseVec, myRough, myNoiseAtten);
    // cout << "VRAY_clusterThis::render() " << "myNoiseVec: " << myNoiseVec.x() << " " << myNoiseVec.x() << " " << myNoiseVec.x() << endl;
 //#ifdef DEBUG
 //   cout << "VRAY_clusterThis::calculateNewInstPosition() " << "noise_bias: " << noise_bias << endl;
 //#endif
 //   // Calculate the new object's position
 //   myPointAttributes.myNewPos[0] = (fpreal) myPointAttributes.myPos.x() +
 //                                   ((dx * myRadius) * noise_bias * SYSsin(static_cast<fpreal>(j + i)));
 //   myPointAttributes.myNewPos[1] = (fpreal) myPointAttributes.myPos.y() +
 //                                   ((dy * myRadius) * noise_bias * SYScos(static_cast<fpreal>(j + i)));
 //   myPointAttributes.myNewPos[2] = (fpreal) myPointAttributes.myPos.z() +
 //                                   ((dz * myRadius) * noise_bias * (SYSsin(static_cast<fpreal>(j + i)) + SYScos(static_cast<fpreal>(j + i))));
 ////   myPointAttributes.myNewPos[2] = ( fpreal ) myPointAttributes.myPos.z() +
 ////                                    ( ( dz * myRadius ) * noise_bias * ( SYScos ( static_cast<fpreal>(j + i)) ) );
 //
 //   if (myDoMotionBlur == CLUSTER_MB_DEFORMATION) {
 //      myPointAttributes.myMBPos[0] = myPointAttributes.myNewPos[0] - myPointAttributes.v.x();
 //      myPointAttributes.myMBPos[1] = myPointAttributes.myNewPos[1] - myPointAttributes.v.y();
 //      myPointAttributes.myMBPos[2] = myPointAttributes.myNewPos[2] - myPointAttributes.v.z();
 //   }
 //#ifdef DEBUG
 //   cout << "VRAY_clusterThis::calculateNewInstPosition() myPos:   "
 //        << myPointAttributes.myPos.x() << " " << myPointAttributes.myPos.y() << " " << myPointAttributes.myPos.z() << endl;
 //   cout << "VRAY_clusterThis::calculateNewInstPosition() newPos: "
 //        << myPointAttributes.myNewPos[0] << " " << myPointAttributes.myNewPos[1] << " " << myPointAttributes.myNewPos[2] << endl;
 //#endif
    return 0;
 }
clampBox()
static void clampBox (UT_BoundingBox & from, const UT_BoundingBox & to) inline static
Definition at line 800 of file VRAY_clusterThisUtil.cpp.
 {
    if(from.vals[0][0] < to.vals[0][0])
       from.vals[0][0] = to.vals[0][0];
    if(from.vals[1][0] < to.vals[1][0])
       from.vals[1][0] = to.vals[1][0];
    if(from.vals[2][0] < to.vals[2][0])
       from.vals[2][0] = to.vals[2][0];
    if(from.vals[0][1] > to.vals[0][1])
       from.vals[0][1] = to.vals[0][1];
    if(from.vals[1][1] > to.vals[1][1])
       from.vals[1][1] = to.vals[1][1];
    if(from.vals[2][1] > to.vals[2][1])
       from.vals[2][1] = to.vals[2][1];
 }
Referenced by VRAY_clusterThis::initialize().
computeDivs()
static int computeDivs (fpreal inc, fpreal min) inline static
Definition at line 906 of file VRAY_clusterThisUtil.cpp.
 {
    int  divs = (int)SYSceil(inc / min);
    if(divs < 1)
       divs = 1;
    else
       if(divs > 4)
          divs = 4;
    return divs;
 }
getRoughBBox()
static void getRoughBBox (UT_BoundingBox & box, UT_BoundingBox & vbox, const GEO_Point * point, const fpreal scale, const GA_ROAttributeRef & voff, fpreal tscale, const UT_Matrix4 & xform) static
********************** MISC. STATIC FUNCTIONS *************************************
Definition at line 755 of file VRAY_clusterThisUtil.cpp.
 {
    fpreal     maxradius;
 //   static fpreal isin45 = 1.0F / SYSsin(M_PI / 4);  // isin45 = 1.41421
    UT_Vector3    pt;
    maxradius = scale * 0.5F;
 //   maxradius = SYSmax(scale.x(), scale.y()) * isin45 * 0.5F;
    pt = UT_Vector3(-maxradius, -maxradius, 0) * xform;
    box.initBounds(pt);
    pt = UT_Vector3(-maxradius,  maxradius, 0) * xform;
    box.enlargeBounds(pt);
    pt = UT_Vector3(maxradius, -maxradius, 0) * xform;
    box.enlargeBounds(pt);
    pt = UT_Vector3(maxradius,  maxradius, 0) * xform;
    box.enlargeBounds(pt);
    box.translate(point->getPos());
    vbox = box;
    UT_Vector3  vel;
    int      i;
    fpreal      amount;
    vel = point->getValue<UT_Vector3>(voff);
 //         std::cout << "getRoughBBox() vel: " << vel << std::endl;
    for(i = 0; i < 3; i++) {
          amount = vel(i) * tscale;
          if(amount < 0)
             vbox.vals[i][1] -= amount;
          else
             vbox.vals[i][0] -= amount;
       }
 //         std::cout << "getRoughBBox() amount: " << amount << std::endl;
 //   std::cout << "getRoughBBox() \nbox: " << box << "vbox: " << vbox << std::endl;
 }
Referenced by VRAY_clusterThis::initialize().
myPasses()
static short int myPasses (int mode) static
Definition at line 834 of file VRAY_clusterThisUtil.cpp.
 {
    static short int num_passes; // keep track of how many times the DSO gets called
    if(mode)
       return num_passes;
    else
       num_passes++;
    return 0;
 }
Referenced by VRAY_clusterThis::render().
testClampBox()
static int testClampBox (const UT_BoundingBox & from, const UT_BoundingBox & to) inline static
Definition at line 816 of file VRAY_clusterThisUtil.cpp.
 {
    if(from.vals[0][0] < to.vals[0][0])
       return 1;
    if(from.vals[1][0] < to.vals[1][0])
       return 1;
    if(from.vals[2][0] < to.vals[2][0])
       return 1;
    if(from.vals[0][1] > to.vals[0][1])
       return 1;
    if(from.vals[1][1] > to.vals[1][1])
       return 1;
    if(from.vals[2][1] > to.vals[2][1])
       return 1;
    return 0;
 }
Referenced by VRAY_clusterThis::initialize().